### ISSUE TITLE
SwimSprint not working

### ISSUE THREAD

**Issue by RatyBruh** [KenjieDec/SwimSprint#1]
Hello! I am playing raft with a friend, and when he tries to sprint in the water, he can, and I can do it the first time I log on, and then when I walk upon the raft again and jump down, it stops working.

**Comment by KenjieDec** [comment]
Its looks like a bug when you Do ALT+Tab ( Opening other window ) while
Clicking on Shift, and still clicking on Shift While opening Raft Game.

Or

When you open raft game, you clicked sprint button too fast.

I'm sorry for that Error, Still finding on Fix :D
