### ISSUE TITLE
incompability with no-hunger mods

### ISSUE THREAD

**Issue by phpmoli** [KenjieDec/SwimSprint#2]
Hello,
There were reports on the Raftmodding discord that my (https://www.raftmodding.com/mods/no-hunger ) and one other's (https://www.raftmodding.com/mods/stat-modifier ) no-hunger mod is not working. After some detective work, it became clear that the reporters had your mod installed.

I've looked at the codes, and i think the incompability can only be solved on your side, it can not be solved on my side.

Can you please make a check, when you change the nourishment values, that they are not 0, and when they are, then you do not make the change?
Something like change from
```
                    GameModeValueManager.GetCurrentGameModeValue().nourishmentVariables.foodDecrementRateMultiplier = 1.2f;
                    GameModeValueManager.GetCurrentGameModeValue().nourishmentVariables.thirstDecrementRateMultiplier = 1.2f;
```
to
```
if (GameModeValueManager.GetCurrentGameModeValue().nourishmentVariables.foodDecrementRateMultiplier > 0f) {
                    GameModeValueManager.GetCurrentGameModeValue().nourishmentVariables.foodDecrementRateMultiplier = 1.2f;
}
if (GameModeValueManager.GetCurrentGameModeValue().nourishmentVariables.thirstDecrementRateMultiplier > 0f) {
                    GameModeValueManager.GetCurrentGameModeValue().nourishmentVariables.thirstDecrementRateMultiplier = 1.2f;
}
```
all the **3 places** in the code.
Thank you.

**Comment by KenjieDec** [comment]
Sure! Sorry for the inconvenience!
Feel free to re-open or open a new issue if the new update doesn't fix anything.

**Comment by phpmoli** [comment]
Thanks for the response!
I didnt check the mod, just the code, there is 1 line duplicated here:
```
            if (GameModeValueManager.GetCurrentGameModeValue().nourishmentVariables.thirstDecrementRateMultiplier > 0f) {
                GameModeValueManager.GetCurrentGameModeValue().nourishmentVariables.thirstDecrementRateMultiplier = 1f;
            }
            GameModeValueManager.GetCurrentGameModeValue().nourishmentVariables.thirstDecrementRateMultiplier = 1f;
```
I guess, it is a copy-paste editing error

**Comment by KenjieDec** [comment]
Fixed! Sorry for that.
