### ISSUE TITLE
SwimSprint Outdated code

### ISSUE THREAD

**Issue by FranzFischer78** [KenjieDec/SwimSprint#3]
Hey, I'm from the RaftModding staff. A user got issues with your swim sprint mod on the discord server. It looks like your mod is not up to date but it's a simple fix.

Just change the line 26 of your main cs file to 
`if (!LoadSceneManager.IsGameSceneLoaded)`

If your are on discord feel free to message me FranzFischer#6710 or join the raftmodding discord server ;)

**Comment by KenjieDec** [comment]
Thank you so much! Fixed!

**Comment by FranzFischer78** [comment]
You're welcome 😉

**Comment by FranzFischer78** [comment]
Are you on the raftmodding discord btw?

**Comment by KenjieDec** [comment]
Yes :)

**Comment by FranzFischer78** [comment]
How can we contact you there 😅 haven't found your username 😅

**Comment by KenjieDec** [comment]
it's Seena#5656
